language: java
jdk:
  - openjdk17  # Specify the JDK version you want to use

install:
  - mvn install -DskipTests=true  # Install dependencies, but skip tests to speed up the process

script:
  - mvn clean package -DskipTests  # Build the project (skip tests)

deploy:
  provider: azure_web_apps
  app: eshwar-backend  # The name of your Azure App Service
  subscription_id: $AZURE_SUBSCRIPTION_ID
  client_id: $AZURE_CLIENT_ID
  client_secret: $AZURE_CLIENT_SECRET
  tenant_id: $AZURE_TENANT_ID
  resource_group: eshwar  # The name of your Azure Resource Group
  on:
    branch: main  # Deploy only on changes to the main branch (adjust as needed)
